name: workflow-test

on:
  push:
    branches:
    -  main

  workflow_dispatch: 

jobs:

     what-if:
      runs-on: ubuntu-latest
      environment: validate
      steps:     
        - uses: azure/login@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
        - name: Checkout
          uses: actions/checkout@v1
        - name: Azure CLI script file
          uses: Azure/cli@v1
          with:
              azcliversion: 2.33.1
              inlineScript: |
                        az account show